[project]
name = "llmdev"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "jupyterlab>=4.5.4",
    "notebook>=7.5.3",
    "pyright>=1.1.408",
    "ruff>=0.15.0",
    "ruff-lsp>=0.0.62",
    "voila>=0.5.11",
]
